printWidth: 120
tabWidth: 2
useTabs: false
semi: true
singleQuote: false
quoteProps: "as-needed"
jsxSingleQuote: false
trailingComma: "es5"
bracketSpacing: true
arrowParens: "always"
vueIndentScriptAndStyle: false
endOfLine: "lf"
embeddedLanguageFormatting: "off"
